/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package rso.at;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum FileType implements org.apache.thrift.TEnum {
  FILE(0),
  DIRECTORY(1);

  private final int value;

  private FileType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static FileType findByValue(int value) { 
    switch (value) {
      case 0:
        return FILE;
      case 1:
        return DIRECTORY;
      default:
        return null;
    }
  }
}
